kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
kubeadmConfigPatches:
  - |
    kind: ClusterConfiguration
    metadata:
      name: config
    apiServer:
      extraArgs:
        enable-admission-plugins: NodeRestriction,PodSecurityPolicy
nodes:
- role: control-plane
- role: worker
networking:
  disableDefaultCNI: true 
  podSubnet: 192.168.0.0/16