kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: basic-view-edit
rules:
- apiGroups:
  - ""
  - apps
  - extensions
  resources:
  - pods
  - pods/exec
  - deployments
  - services
  - persistentvolumeclaims
  verbs:
  - get
  - list 
  - watch
  - create 
  - update 
  - patch
  - delete
